### ISSUE TITLE
zip on Linux requires CD to the unzipped dir

### ISSUE THREAD

**Issue by HMaker** [mathieures/convert-apk#3]
https://github.com/mathieures/convert-apk/blob/b1578722dc307597c2d9e660fee4bde507a00760/uncompress-resources.sh#L37-L40

should be
```bash
compress_with_zip()
{
    pushd $unzipped >/dev/null
    zip -n resources.arsc -qr "$dst" *
    popd >/dev/null
}
```
otherwise zip will copy the absolute path of the unzipped dir starting from `/` root dir. Later when installing the apk the installer will fail to find the `AndroidManifest.xml` file because it's not in the root of the archive anymore.

Zip version
```
❯ zip --version
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
Currently maintained by E. Gordon.  Please send bug reports to
the authors using the web page at www.info-zip.org; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip,
as of above date; see http://www.info-zip.org/ for other sites.

Compiled with gcc 6.3.0 20170415 for Unix (Linux ELF).
```

**Comment by mathieures** [comment]
Good catch, thank you for opening the issue! It is now fixed thanks to #4 and #5 (both include a `cd` to the unzipped folder.
